### ISSUE TITLE
(node:71664) [FSTDEP005] FastifyDeprecation "request.connection"

### ISSUE THREAD

**Issue by marlon-chagas** [pbojinov/request-ip#86]
Im using request-ip in my fastify application and after I updated to Fastify@4 Im getting following warning:

```
(node:71664) [FSTDEP005] FastifyDeprecation: You are accessing the deprecated "request.connection" property. 
Use "request.socket" instead.
    at Object.emit (xxxx/process-warning/index.js:52:13)
    at Request.get (xxxx/fastify/lib/request.js:211:17)
    at Object.getClientIp (xxxx/request-ip/lib/index.js:88:21)
    at resolveIp (xxxx/dist/middlewares/my-file.js:7:89)
    at Object.fastifyReqLogger [as req] (xxxxx/dist/main.js:62:69)
    at Pino.asJson (xxxx/pino/lib/tools.js:132:33)
    at Pino.write (xxxx/pino/lib/proto.js:205:28)
    at Pino.LOG [as info] (xxxx/pino/lib/tools.js:62:21)
    at Object.routeHandler [as handler] (xxxx/fastify/lib/route.js:470:19)
    at Router.callHandler (xxxx/find-my-way/index.js:398:14)"
```

It is a simple fix by modifying the following code snippet:
![image](https://user-images.githubusercontent.com/120677604/235794582-6794aa58-b690-491c-9a8d-b7a31ffe0c1a.png)

as the latest version of fastify suggests.

Can I open PR with that fix?

**Comment by Ismaaa** [comment]
Your contribution sounds valuable @marlon-chagas ! Please do open a PR with your fix.

**Comment by System233** [comment]
@pbojinov

**Comment by System233** [comment]
Repository not maintained.
For `fastify` OR `express` you probably don't need `request-ip`, they have built-in support, check out [fastify-trustproxy](https://github.com/fastify/fastify/blob/main/docs/Reference/Server.md#trustproxy) or [expess-behind-proxies](https://expressjs.com/en/guide/behind-proxies.html).

**Comment by bybraveHQ** [comment]
The warning comes from reading `req.connection.remoteAddress` — `connection` is deprecated in favour of `req.socket` (FSTDEP005).

Fixed in the drop-in fork [@bybrave/request-ip2](https://www.npmjs.com/package/@bybrave/request-ip2): it prefers `req.socket` and only falls back to `req.connection` when the socket is absent, so the deprecation warning is gone while resolution stays identical. 0 dependencies, dual ESM+CJS, built-in types. See #25 for the full set of fixes.
